"""drop notified_at from tasks

Revision ID: 782564aabf1a
Revises: 9426a98c396e
Create Date: 2026-09-14 13:22:58.479238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '782564aabf1a'
down_revision: Union[str, Sequence[str], None] = '9426a98c396e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'notified_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('notified_at', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
