"""add pending_due_at for reschedule disambiguation

Revision ID: a8cb8ce442f2
Revises: d30149e37a6a
Create Date: 2026-09-14 14:50:53.360918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8cb8ce442f2'
down_revision: Union[str, Sequence[str], None] = 'd30149e37a6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pending_clarifications', sa.Column('pending_due_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pending_clarifications', 'pending_due_at')
    # ### end Alembic commands ###
